name: cloud_firestore_odm_example
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.5
  cloud_firestore_odm: ^1.1.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  meta: ^1.12.0

dev_dependencies:
  build_runner: ^2.4.2
  cloud_firestore_odm_generator:
    path: ../../cloud_firestore_odm_generator
  cloud_firestore_odm_generator_integration_test:
    path: ../../cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  http: ^1.0.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mockito: ^5.0.0

dependency_overrides:
  cloud_firestore_odm:
    path: ../

flutter:
  uses-material-design: true
