name: cloud_firestore_odm_generator
description: A code generator for cloud_firestore_odm.
homepage: https://firebase.flutter.dev/docs/firestore/odm
repository: https://github.com/firebaseextended/firestoreodm-flutter
version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.12.0 <8.0.0"
  build: ^2.4.1
  build_config: ^1.1.2
  cloud_firestore_odm: ^1.1.0
  collection: ^1.18.0
  freezed_annotation: ^3.0.0
  # Can be removed once this is fixed https://github.com/dart-lang/graphs/issues/86
  graphs: ^2.3.1
  json_annotation: ^4.9.0
  meta: ^1.12.0
  recase: ^4.1.0
  source_gen: ^2.0.0
  source_helper: ^1.3.4

dev_dependencies:
  build_runner: ^2.4.8
  expect_error: ^1.0.8
  json_serializable: ^6.9.4
  matcher: ^0.12.16
  test: ^1.25.1
