name: cloud_firestore_odm
description: An ODM for Firebase Cloud Firestore (cloud_firestore).
homepage: https://github.com/firebaseextended/firestoreodm-flutter
repository: https://github.com/firebaseextended/firestoreodm-flutter
version: 1.0.0-dev.88

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
