name: cloud_firestore_odm
description: An ODM for Firebase Cloud Firestore (cloud_firestore).
homepage: https://github.com/firebaseextended/firestoreodm-flutter
repository: https://github.com/firebaseextended/firestoreodm-flutter
version: 1.1.0

false_secrets:
  - example/**

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.2
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.1
