name: cloud_firestore_odm_generator_integration_test
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.0
  cloud_firestore_odm: ^1.0.0-dev.85
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  meta: ^1.12.0

dev_dependencies:
  build_runner: ^2.4.2
  cloud_firestore_odm_generator: ^1.0.0-dev.86
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: '>=6.6.1 <7.0.0'

flutter:
  uses-material-design: false
