name: cloud_firestore_odm_generator_integration_test
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.2
  cloud_firestore_odm: ^1.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  meta: ^1.12.0

dev_dependencies:
  build_runner: ^2.4.8
  cloud_firestore_odm_generator:
    path: ../
  flutter_test:
    sdk: flutter
  freezed: ^3.0.2
  json_serializable: ^6.9.4
  test: ^1.25.1
  firebase_core_platform_interface: ^5.0.0

dependency_overrides:
  cloud_firestore_odm:
    path: ../../cloud_firestore_odm

flutter:
  uses-material-design: false
